language: python
python:
    - "3.6"
before_install:
    - pip install pytest pytest-cov
    - pip install coveralls
script:
    - pytest
    - pip install - python -m pytest . --cov=.
after_success:
    - coveralls
